config/routes.rb
Rails.application.routes.draw do
  root 'users/users#top'

  devise_for :users,
    path: '',
    path_names: {
      sign_up: '',
      sign_in: 'login',
      sign_out: 'logout',
      registration: "signup",
  },
    controllers: {
      registrations: "users/devise/registrations",
      sessions: "users/devise/sessions"
  }

  scope module: :users do
    get 'about', to: 'users#about', as: 'about'
    # 商品検索に関わるアクション
    get 'search/search_api', as: 'rakuten_api'
    get 'search/index', as: 'result'
    get 'search/book_title'
    get 'search/total', as: 'search_total'
    get 'search/results', as: 'search_results'
    # user_titlesに関わるアクション
    get 'user_titles/other/:user_id', to: 'user_titles#index_other', as: 'user_titles_other'
    patch 'user_titles/update_all', as: 'update_all_titles'
    resources :user_titles, except: [:edit]
    get 'titles', to: 'titles#index', as: 'titles'
    # book_shelvesに関わるアクション
    get 'book_shelves/nil', as: 'book_shelf_nil'
    delete 'book_shelves/destroy_all', as: 'book_shelves_destroy'
    get 'book_shelves/other/:user_id', to: 'book_shelves#index_other', as: 'book_shelves_other'
    get 'book_shelf/other/:id', to: 'book_shelves#show_other', as: 'book_shelf_other'
    resources :book_shelves, except: [:new, :edit]
    # userに関するアクション
    get 'users/search_id'
    get 'users/search_mail'
    get 'users/search'
    get 'users/home', as: "user_home"
    get 'users/notification', as: "user_notification"
    resources :users, except: [:index, :create, :new] do
      # フォロー機能に関わるアクション
      resource :relationships, only: [:create, :destroy]
      get 'follows', to: 'relationships#follower', as: 'follows'
      get 'followers', to: 'relationships#followed', as: 'followers'
    end
  end

  devise_for :admins, controllers: {
    sessions: "admins/devise/sessions",
    passwords: "adminss/devise/passwords",
    registrations: "admins/devise/registrations"
  }
end

app/controllers/users/book_shelves_controller.rb
class Users::BookShelvesController < ApplicationController
  before_action :authenticate_user!, except: [:index_other, :show_other]

  def index
    @book_shelves = current_user.book_shelves
    # 本棚が削除されたままでどの本棚にも入っていない書籍
    @lost_titles = current_user.user_titles.where(book_shelf_id: nil)
    @book_shelf = BookShelf.new
  end

  def index_other
    @user = User.find(params[:user_id])
    @book_shelves = @user.book_shelves.where(is_public: true)
  end

  def create
    # nilから来た場合
    if params[:numbers]
      @book_shelf =  BookShelf.find(params[:BookShelf][:chosen_id])
      change_flags = JSON.parse(params[:numbers])
      i = 0
      change_flags.count.times do
        if change_flags[i][1] == 1
          UserTitle.find(change_flags[i][0]).update(book_shelf_id: @book_shelf.id)
        end
        i += 1
      end
      redirect_to book_shelf_path(@book_shelf)
    else
      if params[:book_shelf][:name].present?
        current_user.book_shelves.create!(name: params[:book_shelf][:name])
        redirect_to book_shelves_path
      else
        flash[:notice] = "本棚名が入力されていません"
        redirect_back(fallback_location: root_path)
      end
    end
  end

  def show
    @book_shelf = BookShelf.find(params[:id])
    if current_user == @book_shelf.user
      # 現在の本棚に入っている書籍
      @user_titles_this = @book_shelf.user_titles
      # それ以外の書籍を取り出し、本棚順にソートする
      @user_titles_others = current_user.user_titles.where.not(book_shelf_id: @book_shelf.id).order("book_shelf_id desc")
      # 本棚未登録の本
      @user_titles_nil = current_user.user_titles.where(book_shelf_id: nil) 
    else
      flash[:notice] == "アクセス権がありません"
      redirect_to root_path
    end
  end

  # is_public: trueの他人の本棚詳細画面
  def show_other
    @book_shelf = BookShelf.find(params[:id])
    if @book_shelf.is_public
      @user_titles = @book_shelf.user_titles
    else
      flash[:notice] = "入力されたidの本棚は非公開設定です"
      redirect_to root_path
    end
  end

  # 本棚に入っていない書籍を入れてある本棚
  def nil
    @book_shelf = BookShelf.new
    @user_titles_this = current_user.user_titles.where(book_shelf_id: nil)
    @user_titles_others = current_user.user_titles.where.not(book_shelf_id: nil).order("book_shelf_id desc")
  end

  def update
    # 本棚更新アクション
    @book_shelf = BookShelf.find(params[:id])
    @book_shelf.update(book_shelf_params)
    # 登録書籍一括変更アクション
    change_flags = JSON.parse(params[:numbers])
    # 元々本棚に登録されていた書籍数
    default_titles = @book_shelf.user_titles.ids.count
    i = 0
    # チェックが外されていたら未登録書籍に移動する
    default_titles.times do
      if change_flags[i][1] == 0
        UserTitle.find(change_flags[i][0]).update(book_shelf_id: nil)
      end
      i += 1
    end
    # チェックされていたらこの本棚に登録する
    (change_flags.count - default_titles).times do
      if change_flags[i][1] == 1
        UserTitle.find(change_flags[i][0]).update(book_shelf_id: @book_shelf.id)
      end
      i += 1
    end
    redirect_to book_shelf_path(@book_shelf)
  end

  def destroy
    BookShelf.find(params[:id]).destroy!
    redirect_to book_shelves_path
  end

  def destroy_all
    current_user.book_shelves.destroy_all
    redirect_to book_shelves_path
  end

  private
  def book_shelf_params
    params.require(:book_shelf).permit(:id, :name, :is_public)
  end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def follower
    @user = User.find(params[:user_id])
    @users = @user.following_user
  end

  def followed
    @user = User.find(params[:user_id])
    @users = @user.follower_user
  end
end

app/controllers/users/search_controller.rb
class Users::SearchController < ApplicationController
  before_action :authenticate_user!

  # 未発売の商品を弾くために導入
  require 'date'
  require 'json'

  def search_api
    if params[:keyword_new]
      # 検索ワードの整形
      keyword = params[:keyword_new].strip
      uri = URI.parse(URI.encode("https://app.rakuten.co.jp/services/api/BooksBook/Search/20170404?format=json&title=#{keyword}&outOfStockFlag=1&sort=-releaseDate&formatVersion=2&applicationId=#{ENV['RWS_APPLICATION_ID']}"))
      json = Net::HTTP.get(uri)
      # api側のエラーの場合も検索結果0を返す
      unless JSON.parse(json)["error"].present?
        @results = date_prefix(JSON.parse(json))
        sort_by_date(@results)
        split_title(@items)
      end
    end
    render :index
  end

  # search_apiの結果表示
  def index
  end

  # DB内のデータ（ユーザ、書籍を）検索するためのページ
  def total
  end

  # indexにおけるmodalの情報処理
  def book_title
    title = params[:title].split(',')
    @items = []
    n = 0
    title.count.times do
      results = Title.where('name like ?', "%#{title[n]}%")
      if results.present?
        # 存在する書籍をすべて@itemsに追加する
        i = 0
        results.count.times do
          @items.push(results[i])
          i += 1
        end
      end
      n += 1
    end
    # 重複して追加したものを削除
    @items.uniq!
    render json: @items
  end

  # ユーザ、登録タイトル総合検索
  def results
    keyword = params[:keyword_db].strip
    # id検索をした際に@を半角に整形
    keyword.gsub(/＠/,"@")
    # Title,Userそれぞれの結果を入れるための形で配列を生成
    @title_results = []
    @user_results = []
    # タイトルあいまい検索
    title_results = Title.where('name like ?', "%#{keyword}%")
    if title_results.present?
      i = 0
      title_results.count.times do
        @title_results.push(title_results[i])
        i += 1
      end
      @title_results.uniq!
    end
    # ユーザ名あいまい検索
    user_results = User.where('name like ?', "%#{keyword}%")
    if user_results.present?
      i = 0
      user_results.count.times do
        @user_results.push(user_results[i])
        i += 1
      end
    end
    # ユーザidあいまい検索
    if keyword[0] == "@"
      user_results_by_id = User.where('elastic_id like ?', "%#{keyword[1,keyword.length]}%")
      i = 0
      user_results_by_id.count.times do
        @user_results.push(user_results_by_id[i])
        i += 1
      end
    end
    unless @user_results.blank?
      @user_results.uniq!
    end
    render :total
  end

  private
  # salesDateのフォーマットを整える
  def date_prefix(results)
    if results['count'] != 0
      results['Items'].each do |item|
        # salesDateを取り出してその文字列に対してregex
        date = item['salesDate']
        date = date.gsub(/頃|下旬|中旬|上旬/,'')
        date = date.gsub(/\A\d{4}.\z/,'\&1月')
        date = date.gsub(/\A\d{4}.\d{2}.\z/,'\&1日')
        date = date.gsub(/\A\d{4}.\d{1}.\z/,'\&1日')
        date = Date.strptime(date, '%Y年%m月%d日')
        item['salesDate'] = date
      end
    else
      # 検索結果0の場合
      false
    end
  end

  # 発売日が今日までのものだけを表示する
  def sort_by_date(results)
    if results
      @items = []
      results.each do |item|
        if Date.today > item['salesDate']
          @items.push(item)
        end
      end
    end
  end

  # 書籍タイトルの分割
  def split_title(results)
    if results
      @titles = []
      results.each do |item|
        title = item['title']
        # 全角スペースを半角に,半角スペースで区切る
        title = item['title'].gsub(/\p{blank}/,' ').split(' ')
        @titles.push(title)
      end
    end
  end
end

app/controllers/users/titles_controller.rb
class Users::TitlesController < ApplicationController
  def index
    @titles = Title.all
  end
end

app/controllers/users/user_titles_controller.rb
class Users::UserTitlesController < ApplicationController
  before_action :authenticate_user!, except: [:index_other, :show]
  before_action :bookshelf_validation, only: [:create, :update]
  before_action :usertitle_validation, only: [:create]

  def index
    @user_titles = current_user.user_titles.order('book_shelf_id desc')
  end

  def index_other
    @user = User.find(params[:user_id])
    @user_titles = @user.public_user_titles
  end

  def show
    @user_title = UserTitle.find(params[:id])
    max = @user_title.volumes.max
    # 10巻区切りにした場合の区切り個数と最後の区切りにおける巻数
    @title_count = [@user_title.volumes.max.fdiv(10).ceil, max - (max / 10) * 10]
    # maxが10の倍数の際には10巻とする
    if @title_count[1] == 0
      @title_count[1] = 10
    end
    # current_userのみ編集もできるように
    if  user_signed_in? && current_user.book_shelves.present?
      @book_shelves = current_user.book_shelves
    end
  end

  def new
    # 新規登録書籍かどうかの分岐
    if params[:id]
      @book = Title.find(params[:id])
      if current_user.user_titles.find_by(title_id: @book.id).present?
        redirect_to user_title_path(current_user.user_titles.find_by(title_id: @book.id))
      end
    else
      @title = params[:title]
      # 登録する書籍が既に存在するかどうかチェック
      if Title.find_by(name: @title).present?
        @book = Title.find_by(name: @title)
      else
        # API検索結果による元の書籍名
        @row_title = params[:row_title]
        # 新規タイトル作成
        @book = Title.new(
          name: params[:title],
          author: params[:author],
          publisher: params[:publisher],
        )
      end
    end
    @user_title = UserTitle.new
    # ユーザが本棚を持っているかどうか
    if current_user.book_shelves.present?
      @book_shelves = current_user.book_shelves
    end
  end

  def create
    # 本棚に関する操作
    # ユーザが既存の本棚を選択した場合
    if params[:option] == "choice"
      @book_shelf = BookShelf.find(params[:BookShelf][:chosen_id])
    # 本棚が存在しない場合、存在するが新しい本棚を作るを選択した場合
    else
      current_user.book_shelves.create!(name: params[:name])
      @book_shelf = current_user.book_shelves.last
    end
    # 登録する書籍に関する操作
    # DB内に既存の書籍の場合
    if params[:user_title][:id]
      @title = Title.find(params[:user_title][:id])
    # DB内に存在せず、新規登録する書籍の場合
    else
      Title.create!(
        name: params[:user_title][:name],
        author: params[:user_title][:author],
        publisher: params[:user_title][:publisher]
      )
      @title = Title.last
    end
    # 所持巻数の入力
    start_vol = params[:start_vol].to_i
    end_vol = params[:end_vol].to_i
    vol = [*start_vol..end_vol]
    current_user.user_titles.create!(
      book_shelf_id: @book_shelf.id,
      title_id: @title.id,
      volume: vol.to_json
    )
    redirect_to book_shelves_path
  end

  def update
    @user_title = UserTitle.find(params[:id])
    numbers = JSON.parse(params[:numbers])
    # 新しい最終巻
    new_max = numbers.rindex(1) + 1
    vol = []
    i = 1
    new_max.times do
      if numbers[i - 1] == 1
        vol.push(i)
      end
      i += 1
    end
    unless params[:end_vol] == ""
      # 新規追加巻数の最終巻
      end_vol = params[:end_vol].to_i
      vol.push(*(@user_title.volumes.max + 1)..end_vol)
    end
    if params[:option] == "choice"
      @book_shelf = BookShelf.find(params[:user_title][:book_shelf_id])
    else
      current_user.book_shelves.create(name: params[:name])
      @book_shelf = current_user.book_shelves.last
    end
    @user_title.update(
      book_shelf_id: @book_shelf.id,
      volume: vol.to_json)
    redirect_to user_titles_path
  end

  def update_all
    @book_shelf =  BookShelf.find(params[:BookShelf][:chosen_id])
    change_flags = JSON.parse(params[:numbers])
    i = 0
    change_flags.count.times do
      if change_flags[i][1] == 1
        UserTitle.find(change_flags[i][0]).update(book_shelf_id: @book_shelf.id)
      end
      i += 1
    end
    redirect_to user_titles_path
  end

  def destroy
    @user_title = UserTitle.find(params[:id])
    @user_title.destroy!
    redirect_to user_titles_path
  end

  private
  # newアクションにおいて受け渡されるパラメータが多いためcreateアクション前にバリデーションをする。
  def bookshelf_validation
    unless params[:option] == "choice"
      unless params[:name].present?
        flash[:notice] = "本棚名が入力されていません"
        redirect_back(fallback_location: root_path)
      end
    end
  end

  def usertitle_validation
    unless params[:user_title][:id]
      unless params[:user_title][:name].present?
        flash[:notice] = "書籍名が入力されていません"
        redirect_back(fallback_location: root_path)
      end
    end
  end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :authenticate_user!, only: [:home, :notification, :edit, :update, :destroy]

  def top
    @new_titles = Title.all.order('id desc').take(10)
  end

  def about
  end

  def home
    @users = current_user.follower_user
    @contents = current_user.contents
  end

  def notification
    @users = current_user.follower_user.order('created_at desc')
    @contents = current_user.contents
    @users_today = range_contents(@users, 0)
    @contents_today = range_contents(@contents, 0)
    @users_weekly = range_contents(@users, 7) - @users_today
    @contents_weekly = range_contents(@contents, 7) - @contents_today
    @users_monthly = range_contents(@users, 30) - range_contents(@users, 7)
    @contents_monthly = range_contents(@contents, 30) - range_contents(@contents, 7)
  end

  def search
    # 登録書籍からユーザを検索する
    @title = Title.find(params[:title_id])
    @user_titles = @title.user_titles.order('id desc')
  end

  def show
    @user = User.find(params[:id])
    @book_shelves = @user.book_shelves.where(is_public: true)
    @user_titles = @user.public_user_titles
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      flash[:notice] = "アクセス権がありません"
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:notice] = "ユーザ情報が変更されました"
    redirect_to user_path(@user)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております"
    redirect_to root_path
  end

  def search_id
    result = User.find_by(elastic_id: params[:id]).present?
    render json: result
  end

  def search_mail
    result = User.find_by(email: params[:email]).present?
    render json: result
  end

  private
  def user_params
    params.require(:user).permit(:id, :name, :elastic_id, :notification_type)
  end

  # start日前から今までのコンテンツを取り出す
  def range_contents(contents, start)
    results = []
    i = 0
    contents.count.times do
      content = contents[i]
      if content.created_at.between?((start).days.ago.midnight, Time.now)
        results.push(content)
      else
        break
      end
      i += 1
    end
    results
  end
end

app/helpers/users/book_shelves_helper.rb
module Users::BookShelvesHelper
end

app/helpers/users/relationships_helper.rb
module Users::RelationshipsHelper
end

app/helpers/users/search_helper.rb
module Users::SearchHelper
end

app/helpers/users/titles_helper.rb
module Users::TitlesHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/helpers/users/users_titles_helper.rb
module Users::UsersTitlesHelper
end

app/views/users/book_shelves/_book_shelf.html.erb
<div class="container">
  <div class="row">
    <h2>
      <% if @book_shelf.id != nil %>
        本棚【<%= @book_shelf.name %>】
        <% if @book_shelf.is_public %>
          <i class="fas fa-unlock"></i>
        <% else %>
          <i class="fas fa-lock"></i>
        <% end %>
        <%= link_to "削除", book_shelf_path, method: :delete, class:"btn btn-danger", data:
        { confirm: "本棚を削除しても中の本は削除されません",
          cancel: "やめる",
          commit: "削除する"
        }, title: "本棚を削除する" %>
      <% else %>
        本棚未設定のシリーズ
      <% end %>
    </h2>
    <table class="table table-bordered table-hover">
      <thead class="thead-light">
        <tr>
          <th>シリーズ名</th>
          <th>著者</th>
          <th>出版社</th>
          <th class="text-center" style="width: 10%">所持巻数</th>
        </tr>
      </thead>
      <tbody>
        <% @user_titles_this.each_with_index do |user_title,i| %>
          <tr id="row-<%= i %>" class="user_title">
            <td><%= user_title.title.name %></td>
            <td><%= user_title.title.author %></td>
            <td><%= user_title.title.publisher %></td>
            <td class="text-center"><%= user_title.volumes.count %></td>
            <div id="tag-info-<%= i %>" data-id="<%= user_title.id %>"></div>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="offset-6">
  <%= form_with(model: @book_shelf, local: true) do |f| %>
    <div class="form-group">
      <label>公開設定</label>
      <div class="form-inline row offset-3">
        <label class="mx-sm-1">非公開</label>
        <%= f.radio_button :is_public, false, class:"mx-sm-3" %>
        <label class="mx-sm-1">公開</label>
        <%= f.radio_button :is_public, true, class:"mx-sm-3" %>
      </div>
    </div>
    <div class="form-gruop row">
      <% if @book_shelf.id != nil %>
        <label>本棚名変更</label>
        <%= f.text_field :name, class: "form-control" %>
      <% else %>
        <label>本棚選択</label>
        <%= collection_select :BookShelf, :chosen_id, current_user.book_shelves, :id, :name, {prompt: false},class: "custom-select" %>
      <% end %>
    </div>
    <div class="form-group row">
      <label>本棚一括変更(色付きが登録対象)</label>
      <table class="table table-sm table-bordered">
        <thead>
          <tr>
            <th>シリーズ名</th>
            <th class="text-center" style="width:25%">現在の本棚</th>
          </tr>
        </thead>
        <%# 擬似的にソートを実現 %>
        <tbody>
          <% @user_titles_this.each_with_index do |user_title,i| %>
            <tr class="title_all table-success" data=<%= user_title.id %> id="title-<%= i %>">
              <td><%= user_title.title.name %></td>
              <td class="text-center">
                <% if @book_shelf.id != nil %>
                  <%= @book_shelf.name %>
                <% else %>
                  未登録
                <% end %>
              </td>
            </tr>
          <% end %>
          <% @user_titles_others.each_with_index do |user_title,i| %>
            <tr class="title_all" data=<%= user_title.id %> id="title-<%= @user_titles_this.count + i %>">
              <td><%= user_title.title.name %></td>
              <td class="text-center"><%= user_title.book_shelf.name %></td>
            </tr>
          <% end %>
          <%# 未登録書籍本棚の場合はスキップ %>
          <% if @user_titles_nil %>
            <% @user_titles_nil.each_with_index do |user_title,i| %>
              <tr class="title_all" data=<%= user_title.id %> id="title-<%= @user_titles_this.count + @user_titles_others.count + i %>">
                <td><%= user_title.title.name %></td>
                <td class="text-center">未登録</td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <%= hidden_field_tag :numbers, "", {id: "numbers"} %>
    </div>
    <div class="form-group text-center">
      <%= f.submit "本棚内容を更新", class: "btn btn-success" %>
    </div>
  <% end %>
  </div>
</div>

app/views/users/book_shelves/index.html.erb
<div class="container">
  <div class="row">
    <h2>
      本棚一覧
      <%= link_to "全本棚削除", book_shelves_destroy_path, method: :delete, class:"btn btn-danger", data:
        { confirm: "本棚を削除しても中の本は削除されません",
          cancel: "やめる",
          commit: "削除する"
        }, title: "本棚を削除する" %>
      </h2>
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr>
          <th style="width: 75%">名前</th>
          <th class="text-center">登録タイトル数</th>
          <th style="width: 8%"></th>
        </tr>
      </thead>
      <tbody>
        <% @book_shelves.each do |book_shelf| %>
          <tr>
            <td class="align-middle">
              <%= link_to book_shelf_path(book_shelf) do %>
                <%= book_shelf.name %>
                <% if book_shelf.is_public %>
                  <i class="fas fa-unlock"></i>
                <% else %>
                  <i class="fas fa-lock"></i>
                <% end %>
              <% end %>
            </td>
            <td class="text-center align-middle"><%= book_shelf.user_titles.count %></td>
            <td class="text-center"><%= link_to "削除", book_shelf_path(book_shelf), method: :delete, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
        <tr>
          <td><%= link_to "未登録書籍", book_shelf_nil_path%></td>
          <td class="text-center"><%= @lost_titles.count %></td>
          <td></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="row float-right">
  <h4>新規本棚追加</h4>
  <%= form_with(model: @book_shelf, local: true) do |f| %>
    <div class="form-inline">
      <%= f.text_field :name, class: "form-control mx-sm-3" %>
      <%= f.submit "追加", class: "btn btn-success" %>
    </div>
  <% end %>
  </div>
</div>

app/views/users/book_shelves/index_other.html.erb
<div class="container">
  <div class="row">
    <h2><%= @user.name %>さんの本棚一覧</h2>
    <table class="table table-bordered">
      <thead class="thead-light">
        <tr>
          <th style="width: 80%">名前</th>
          <th class="text-center">登録タイトル数</th>
        </tr>
      </thead>
      <tbody>
        <% @book_shelves.each do |book_shelf| %>
          <tr>
            <td class="align-middle">
              <%= link_to book_shelf_other_path(book_shelf) do %>
                <%= book_shelf.name %>
              <% end %>
            </td>
            <td class="text-center align-middle"><%= book_shelf.user_titles.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/book_shelves/nil.html.erb
<%= render 'book_shelf' %>

app/views/users/book_shelves/show.html.erb
<h1>Users::BookShelves#show</h1>
<p>Find me in app/views/users/book_shelves/show.html.erb</p>

app/views/users/book_shelves/show_other.html.erb
<div class="container">
  <div class="row">
    <h2><%= @book_shelf.user.name %>さんの本棚【<%= @book_shelf.name %>】</h2>
    <table class="table table-bordered table-hover">
      <thead class="thead-light">
        <tr>
          <th>シリーズ名</th>
          <th>著者</th>
          <th>出版社</th>
          <th class="text-center" style="width: 10%">所持巻数</th>
        </tr>
      </thead>
      <tbody>
        <% @user_titles.each_with_index do |user_title,i| %>
          <tr id="row-<%= i %>" class="user_title">
            <td><%= user_title.title.name %></td>
            <td><%= user_title.title.author %></td>
            <td><%= user_title.title.publisher %></td>
            <td class="text-center"><%= user_title.volumes.count %></td>
            <div id="tag-info-<%= i %>" data-id="<%= user_title.id %>"></div>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>