config/routes.rb
Rails.application.routes.draw do
  root 'users/users#top'

  devise_for :users,
    path: '',
    path_names: {
      sign_up: '',
      sign_in: 'login',
      sign_out: 'logout',
      registration: "signup",
  },
    controllers: {
      registrations: "users/devise/registrations",
      sessions: "users/devise/sessions"
  }

  scope module: :users do
    get 'about', to: 'users#about', as: 'about'
    # 商品検索に関わるアクション
    get 'search/search_api', as: 'rakuten_api'
    get 'search/index', as: 'result'
    get 'search/book_title'
    get 'search/total', as: 'search_total'
    get 'search/results', as: 'search_results'
    # user_titlesに関わるアクション
    get 'user_titles/other/:user_id', to: 'user_titles#index_other', as: 'user_titles_other'
    patch 'user_titles/update_all', as: 'update_all_titles'
    resources :user_titles, except: [:edit]
    get 'titles', to: 'titles#index', as: 'titles'
    # book_shelvesに関わるアクション
    get 'book_shelves/nil', as: 'book_shelf_nil'
    delete 'book_shelves/destroy_all', as: 'book_shelves_destroy'
    get 'book_shelves/other/:user_id', to: 'book_shelves#index_other', as: 'book_shelves_other'
    get 'book_shelf/other/:id', to: 'book_shelves#show_other', as: 'book_shelf_other'
    resources :book_shelves, except: [:new, :edit]
    # userに関するアクション
    get 'users/search_id'
    get 'users/search_mail'
    get 'users/search'
    get 'users/home', as: "user_home"
    get 'users/notification', as: "user_notification"
    resources :users, except: [:index, :create, :new] do
      # フォロー機能に関わるアクション
      resource :relationships, only: [:create, :destroy]
      get 'follows', to: 'relationships#follower', as: 'follows'
      get 'followers', to: 'relationships#followed', as: 'followers'
    end
  end

  devise_for :admins, controllers: {
    sessions: "admins/devise/sessions",
    passwords: "adminss/devise/passwords",
    registrations: "admins/devise/registrations"
  }
end

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom">
  <div class="container">
    <div class="row">
      <div class="col-8">
        <h4>更新履歴</h4>
        <ul>
          <li>6/17 ホーム・通知画面導入</li>
          <li>6/25 会員登録時のエラー修正</li>
        </ul>
      </div>
      <div class="col-4">
        <b class="info">要望・お便りはkeishi11433@gmail.comまで</b>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <div class="container">
    <div class="row">
      <div class="col-4">
        <%= link_to "Bookself", root_path, class: "btn btn-outline-light btn-lg offset-3" %>
        <% if user_signed_in? %>
          <div class="form-group form-inline new-book-search">
            <%= form_tag(rakuten_api_path, method: :get) do %>
              <%= text_field_tag :keyword_new, params[:keyword_new], placeholder: "新規書籍検索", class: "form-control" %>
              <%= submit_tag "検索", class: "btn btn-outline-light" %>
            <% end %>
          </div>
        <% else %>
          <div class="form-group form-inline new-book-search offset-4">
            <%= link_to "About", about_path, class: "btn btn-outline-light" %>
          </div>
        <% end %>
      </div>
      <div>
        <% if user_signed_in? %>
          <div class="form-group form-inline nav-bar">
            <%= link_to user_home_path, class: "btn btn-outline-light mx-2" do %>
              <i class="fas fa-home">ホーム</i>
            <% end %>
            <%= link_to user_path(current_user), class: "btn btn-outline-light mx-2" do %>
              <i class="fas fa-address-card">マイページ</i>
            <% end %>
            <%= link_to user_notification_path, class: "btn btn-outline-light mx-2" do %>
              <i class="fas fa-bell">通知</i>
            <% end %>
            <%= form_tag(search_results_path, method: :get) do %>
              <%= text_field_tag :keyword_db, params[:keyword_db], placeholder: "ユーザ・書籍検索", class: "form-control" %>
              <%= submit_tag "検索", class: "btn btn-outline-light mx-2" %>
            <% end %>
            <%= link_to  destroy_user_session_path, method: :delete, class: "btn btn-outline-light" do %>
              <i class="fas fa-sign-out-alt">ログアウト</i>
            <% end %>
          </div>
        <% else %>
          <div class="nav-bar">
            <%= link_to new_user_session_path, class: "btn btn-outline-light" do %>
              <i class="fas fa-sign-in-alt">ログイン</i>
            <% end %>
            <%= link_to new_user_registration_path, class: "btn btn-outline-light" do %>
              <i class="fas fa-user-plus">新規登録</i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookself</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/6f0e0336a0.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/header' %>

  <body>
    <div class="container">
      <p class="is-invalid" id="notice"><%= notice %></p>
    </div>
    <%= yield %>
  </body>

</html>